-- Full Ironwood field order catalog (sundries, rental, equipment, wallcovering)
-- Run after 034_field_tools_admin.sql — replaces prior seed rows in these sections.

DELETE FROM public.field_tools_catalog_items
WHERE section IN ('sundry', 'rental_equipment', 'equipment', 'wallcovering');

INSERT INTO public.field_tools_catalog_items (section, category, name, sort_order)
SELECT v.section, v.category, v.name, v.sort_order
FROM (VALUES
  -- ── Sundries: Masking ──
  ('sundry', 'Masking', 'White Tape 2in', 1),
  ('sundry', 'Masking', 'White Tape 1 1/2', 2),
  ('sundry', 'Masking', 'White Tape 1 in', 3),
  ('sundry', 'Masking', 'Blue Tape 2 in', 4),
  ('sundry', 'Masking', 'Blue Tape 1 ½', 5),
  ('sundry', 'Masking', 'Blue Tape 1in', 6),
  ('sundry', 'Masking', 'Masking Film 99', 7),
  ('sundry', 'Masking', 'Masking Film 48', 8),
  ('sundry', 'Masking', '12" General Purpose Masking Paper', 9),
  ('sundry', 'Masking', '12" Solvent Green Masking Paper', 10),
  ('sundry', 'Masking', 'Poly Red Tape', 11),
  ('sundry', 'Masking', 'Red Rosin', 12),
  ('sundry', 'Masking', 'Painters Plastic 9'' x 400'' .31mil', 13),
  ('sundry', 'Masking', 'Painters Plastic 12'' x 400'' .31mil', 14),
  ('sundry', 'Masking', 'Visqueen Plastic 20'' x 200'' 2 mill', 15),
  ('sundry', 'Masking', 'Visqueen Plastic 12'' x 200'' 2 mill', 16),
  ('sundry', 'Masking', 'Frog Tape 1 1/2 Green', 17),
  ('sundry', 'Masking', 'Frog Tape Delicate 1 1/2 Yellow', 18),
  ('sundry', 'Masking', 'Canvas Drop 4x12', 19),
  ('sundry', 'Masking', 'Canvas Drop 9x12', 20),
  ('sundry', 'Masking', '3M Hand-Masker M3000', 21),
  ('sundry', 'Masking', '3M Hand-Masker Film Blade FB12', 22),
  -- ── Sundries: Sanding ──
  ('sundry', 'Sanding', 'Dual Grit Sanding Sponge', 1),
  ('sundry', 'Sanding', 'Sanding Sheets 150 Grit 20-Pack', 2),
  ('sundry', 'Sanding', 'Sanding Sheets 220 Grit 20-Pack', 3),
  ('sundry', 'Sanding', 'Sanding Sheets 100 Grit 20-Pack', 4),
  ('sundry', 'Sanding', 'Full Circle Radius 150 Grit', 5),
  ('sundry', 'Sanding', 'Full Circle Radius Sanding Tool', 6),
  ('sundry', 'Sanding', 'Orbital Sanding Discs 220 Grit', 7),
  ('sundry', 'Sanding', 'Orbital Sanding Discs 100 Grit', 8),
  ('sundry', 'Sanding', 'Orbital Sanding Discs 80 Grit', 9),
  -- ── Sundries: Patching/Caulking ──
  ('sundry', 'Patching/Caulking', 'Crawfords Spackle', 1),
  ('sundry', 'Patching/Caulking', 'Crawfords Putty', 2),
  ('sundry', 'Patching/Caulking', 'DAP Presto Patch Multi-Purpose Patch', 3),
  ('sundry', 'Patching/Caulking', 'USG Easy Sand 5 3lbs', 4),
  ('sundry', 'Patching/Caulking', 'Bondo All Purpose Putty', 5),
  ('sundry', 'Patching/Caulking', 'Bondo Glazing Spot Putty', 6),
  ('sundry', 'Patching/Caulking', 'White Caulking Tube 10oz', 7),
  ('sundry', 'Patching/Caulking', 'Dripless Ergo-Tech Caulk Gun', 8),
  -- ── Sundries: Solvents ──
  ('sundry', 'Solvents', 'Denatured Alcohol 1gal', 1),
  ('sundry', 'Solvents', 'Acetone 1gal', 2),
  ('sundry', 'Solvents', 'VOC Lacquer Thinner 1gal', 3),
  ('sundry', 'Solvents', 'Lacquer Thinner 1gal', 4),
  ('sundry', 'Solvents', 'Pro Thinner 1gal', 5),
  ('sundry', 'Solvents', 'GOOF OFF 6oz', 6),
  ('sundry', 'Solvents', 'GOOF OFF 16oz', 7),
  ('sundry', 'Solvents', 'GOOF OFF 1gal', 8),
  -- ── Sundries: Other ──
  ('sundry', 'Other', 'Coveralls Spray Suit L', 1),
  ('sundry', 'Other', 'Coveralls Spray Suit XL', 2),
  ('sundry', 'Other', 'Coveralls Spray Suit XXL', 3),
  ('sundry', 'Other', 'Spray Sock', 4),
  ('sundry', 'Other', 'Respirator 8511 10-Pack', 5),
  ('sundry', 'Other', 'Nitrile Gloves 100-Pack XL', 6),
  ('sundry', 'Other', 'Nitrile Gloves 100-Pack L', 7),
  ('sundry', 'Other', 'Nitrile Gloves 100-Pack M', 8),
  ('sundry', 'Other', 'Rags 8LBS', 9),
  ('sundry', 'Other', 'Cardboard Spray Shield 50-Pack', 10),
  ('sundry', 'Other', 'Tack Cloth, 1‐Pack', 11),
  ('sundry', 'Other', 'Strainer Bags Elastic Top Reg Mesh 5gal', 12),
  -- ── Sundries: Spray ──
  ('sundry', 'Spray', 'Graco Green Spray Tip 210', 1),
  ('sundry', 'Spray', 'Graco Green Spray Tip 310', 2),
  ('sundry', 'Spray', 'Graco Blue Spray Tip 517', 3),
  ('sundry', 'Spray', 'Graco Blue Spray Tip 415', 4),
  ('sundry', 'Spray', 'Graco RAC X Guard', 5),
  ('sundry', 'Spray', 'Spray can Black Flat', 6),
  ('sundry', 'Spray', 'Spray can White Semi-Gloss', 7),
  ('sundry', 'Spray', 'Spray can Safety Red', 8),
  ('sundry', 'Spray', 'Spray can Safety Yellow', 9),
  ('sundry', 'Spray', 'Spray can White Primer', 10),
  ('sundry', 'Spray', 'Spray can Grey Primer', 11),
  ('sundry', 'Spray', '3M Super 77 Multipurpose Spray Adhesive', 12),
  -- ── Sundries: Roller Cover/Frames ──
  ('sundry', 'Roller Cover/Frames', '14in 50/50 Blend 1/2 Nap', 1),
  ('sundry', 'Roller Cover/Frames', '14in 50/50 Blend 3/4 Nap', 2),
  ('sundry', 'Roller Cover/Frames', '9in Microfiber 1/2 Nap', 3),
  ('sundry', 'Roller Cover/Frames', '9in Microfiber 3/8 Nap', 4),
  ('sundry', 'Roller Cover/Frames', '9in 50/50 Blend 1/2 Nap', 5),
  ('sundry', 'Roller Cover/Frames', '9in 50/50 Blend 3/4 Nap', 6),
  ('sundry', 'Roller Cover/Frames', '18in 50/50 Blend 1/2 Nap', 7),
  ('sundry', 'Roller Cover/Frames', '18in 50/50 Blend 3/4 Nap', 8),
  ('sundry', 'Roller Cover/Frames', '6in Roller Cover Button End 1/2 Nap 12Pk', 9),
  ('sundry', 'Roller Cover/Frames', '6in Roller No Button End 1/2 Nap 12Pk', 10),
  ('sundry', 'Roller Cover/Frames', '9in Roller Frame Quick release', 11),
  ('sundry', 'Roller Cover/Frames', '14in Roller Frame Quick release', 12),
  ('sundry', 'Roller Cover/Frames', '7in Mini Frame', 13),
  ('sundry', 'Roller Cover/Frames', '2Gal Grid', 14),
  ('sundry', 'Roller Cover/Frames', '5Gal Grid', 15),
  ('sundry', 'Roller Cover/Frames', '2Gal Pail', 16),
  ('sundry', 'Roller Cover/Frames', '5Gal Pail', 17),
  ('sundry', 'Roller Cover/Frames', 'Purdy Nest Dual Roll-Off Bucket', 18),
  ('sundry', 'Roller Cover/Frames', 'Purdy Nest Dual Roll-Off Bucket Liner', 19),
  ('sundry', 'Roller Cover/Frames', 'Plastic Bucket Liner 2Gal', 20),
  ('sundry', 'Roller Cover/Frames', 'Plastic Bucket Liner 5Gal', 21),
  -- ── Rental: Scissor Lift ──
  ('rental_equipment', 'Scissor Lift', '12'' Single Person, Self-Propelled, Electric Genie GR-12', 1),
  ('rental_equipment', 'Scissor Lift', '20'' Single Person, Self-Propelled, Electric Genie GR-20', 2),
  ('rental_equipment', 'Scissor Lift', '25'' Single Person, Self Propelled, Electric MEC MME25', 3),
  ('rental_equipment', 'Scissor Lift', '19'' Platform, Compact', 4),
  -- ── Rental: Boom Lift ──
  ('rental_equipment', 'Boom Lift', '30'' Platform, 2WD, Electric AG Genie Z-30/20N', 1),
  ('rental_equipment', 'Boom Lift', '60'' Platform, 4WD, Gas/LPG AG Genie Z-62/40', 2),
  ('rental_equipment', 'Boom Lift', '65'' Platform w/ Jib, Diesel ST Genie S-65 XC', 3),
  ('rental_equipment', 'Boom Lift', '85'' Platform w/ Jib, Diesel ST Genie S-85 XC', 4),
  -- ── Equipment ──
  ('equipment', 'Sprayer', 'Titan 1040', 1),
  ('equipment', 'Sprayer', 'Titan 840', 2),
  ('equipment', 'Sprayer', 'Titan 440', 3),
  ('equipment', 'Sprayer', 'Graco Mark V', 4),
  ('equipment', 'Sprayer', 'Graco 695', 5),
  ('equipment', 'Sprayer', 'Titan HVLP', 6),
  ('equipment', 'Sprayer', 'Speeflo 8900', 7),
  ('equipment', 'Sprayer', 'Graco 795', 8),
  ('equipment', 'Sprayer', 'Cordless Graco Sprayer', 9),
  ('equipment', 'Misc', 'Air Scrubber', 1),
  ('equipment', 'Misc', 'Air Scrubber (Small)', 2),
  ('equipment', 'Misc', 'Pressure Washer', 3),
  ('equipment', 'Misc', 'Drinking Water', 4),
  ('equipment', 'Vacuum', 'Vacuum Sander', 1),
  ('equipment', 'Vacuum', 'Dewalt HEPA Vacuum', 2),
  ('equipment', 'Ladders', '6'' Ladder', 1),
  ('equipment', 'Ladders', '8'' Ladder', 2),
  ('equipment', 'Scaffolds', '4'' Roll N Fold', 1),
  ('equipment', 'Scaffolds', '5'' Roll N Fold', 2),
  ('equipment', 'WC Tools', 'Wallcovering Table', 1),
  ('equipment', 'WC Tools', 'Miter Saw', 2),
  ('equipment', 'WC Tools', 'Air Compressor', 3),
  ('equipment', 'WC Tools', 'Panel Packout', 4),
  ('equipment', 'WC Tools', 'FRP Packout', 5),
  -- ── Wallcovering: Blades ──
  ('wallcovering', 'Blades', '9mm Carbon Steel Snap Blade 20pk', 1),
  ('wallcovering', 'Blades', '18mm Carbon Steel Snap Blade 20pk', 2),
  ('wallcovering', 'Blades', 'Single Blade 100pk', 3),
  ('wallcovering', 'Blades', 'Carbon Steel Single Edge Razor 100pk', 4),
  -- ── Wallcovering: Misc ──
  ('wallcovering', 'Misc', 'Double Sided Tape', 1),
  ('wallcovering', 'Misc', '2" Staples', 2),
  ('wallcovering', 'Misc', '1 1/2" Staples', 3),
  ('wallcovering', 'Misc', '5/16" Staples', 4),
  ('wallcovering', 'Misc', 'Cardboard Shims', 5),
  ('wallcovering', 'Misc', '3M 77 Spray Glue', 6),
  -- ── Wallcovering: Infill ──
  ('wallcovering', 'Infill', '1/2" Ecocore 49" x 97" 9.5 PCF White', 1),
  ('wallcovering', 'Infill', '1/2" Ecocore 49" x 97" 9.5 PCF Black', 2),
  ('wallcovering', 'Infill', '1" Ecocore 49" x 97" 3 PCF White', 3),
  ('wallcovering', 'Infill', '1" Ecocore 49" x 97" 3 PCF Black', 4),
  ('wallcovering', 'Infill', '1" Ecocore 49" x 97" 6 PCF White', 5),
  ('wallcovering', 'Infill', '1" Ecocore 49" x 97" 6 PCF Black', 6),
  ('wallcovering', 'Infill', '2" Ecocore 49" x 97" 5.4 PCF White', 7),
  ('wallcovering', 'Infill', '2" Ecocore 49" x 97" 5.4 PCF Black', 8),
  ('wallcovering', 'Infill', '1" Fiberglass 49" x 97" 6 PCF', 9),
  ('wallcovering', 'Infill', '2" Fiberglass 49" x 97" 6 PCF', 10),
  -- ── Wallcovering: Track ──
  ('wallcovering', 'Track', '1/2" Square Bottom Load Natural', 1),
  ('wallcovering', 'Track', '1/2" Square Top Load Perimeter Natural', 2),
  ('wallcovering', 'Track', '1/2" Square Top Load Perimeter Black', 3),
  ('wallcovering', 'Track', '1/2" Square Midwall Natural', 4),
  ('wallcovering', 'Track', '1/2" Square Midwall Black', 5),
  ('wallcovering', 'Track', '1/2" Oustside Corner Natural', 6),
  ('wallcovering', 'Track', '5/8" Square Bottom Load Natural', 7),
  ('wallcovering', 'Track', '5/8" Square Bottom Load Black', 8),
  ('wallcovering', 'Track', '5/8" Square Top Load Perimeter Natural', 9),
  ('wallcovering', 'Track', '5/8" Square Top Load Perimeter Black', 10),
  ('wallcovering', 'Track', '5/8" Square Midwall Natural', 11),
  ('wallcovering', 'Track', '5/8" Square Midwall Black', 12),
  ('wallcovering', 'Track', '5/8" Square Side Load Perimeter Natural', 13),
  ('wallcovering', 'Track', '5/8" Square Side Load Perimeter Black', 14),
  ('wallcovering', 'Track', '1" Square Bottom Load Natural', 15),
  ('wallcovering', 'Track', '1" Square Bottom Load Black', 16),
  ('wallcovering', 'Track', '1" Square Side Load Perimeter Natural', 17),
  ('wallcovering', 'Track', '1" Square Side Load Perimeter Black', 18),
  ('wallcovering', 'Track', '1" Square Top Load Perimeter Natural', 19),
  ('wallcovering', 'Track', '1" Square Top Load Perimeter Black', 20),
  ('wallcovering', 'Track', '1" Square Midwall Natural', 21),
  ('wallcovering', 'Track', '1" Square Midwall Black', 22),
  ('wallcovering', 'Track', '1" Bevel Side Load Natural', 23),
  ('wallcovering', 'Track', '1" Bevel Midwall Natural', 24),
  ('wallcovering', 'Track', '1" Square Side Load Perimeter PVC Free Black', 25),
  ('wallcovering', 'Track', '1" Square Top Load Perimeter PVC Free Black', 26),
  ('wallcovering', 'Track', '1" Square Midwall PVC Free Black', 27),
  ('wallcovering', 'Track', '1" Square Bottom Load PVC Free Black', 28),
  ('wallcovering', 'Track', '1.125" Square Bottom Load Black', 29),
  ('wallcovering', 'Track', '1.125" Square Side Load Perimeter Natural', 30),
  ('wallcovering', 'Track', '1.125" Square Side Load Perimeter Black', 31),
  ('wallcovering', 'Track', '1.125" Square Top Load Perimeter Natural', 32),
  ('wallcovering', 'Track', '1.125" Square Top Load Perimeter Black', 33),
  ('wallcovering', 'Track', '1.125" Square Midwall Natural', 34),
  ('wallcovering', 'Track', '1.125" Square Midwall Black', 35),
  ('wallcovering', 'Track', '1" Outside Corner Natural', 36),
  ('wallcovering', 'Track', '2⅛" Square Top Load Perimeter Natural', 37),
  ('wallcovering', 'Track', '2⅛" Square Top Load Perimeter Black', 38),
  ('wallcovering', 'Track', '2⅛" Square Midwall Natural', 39),
  ('wallcovering', 'Track', '2⅛" Square Midwall Black', 40),
  ('wallcovering', 'Track', '2⅛" Square Bottom Load Natural', 41),
  ('wallcovering', 'Track', '2⅛" Square Bottom Load Black', 42),
  -- ── Wallcovering: Air ──
  ('wallcovering', 'Air', 'Staple Gun 5/16"', 1),
  ('wallcovering', 'Air', 'Staple Gun 1 1/2"', 2),
  ('wallcovering', 'Air', 'Staple Gun 2"', 3),
  ('wallcovering', 'Air', 'Compressor w/ Hose', 4)
) AS v(section, category, name, sort_order);

NOTIFY pgrst, 'reload schema';
