-- Apply structured JHA fields. Existing templates keep their steps.
-- Slugs that are not in the library are skipped.
update public.aha_library
set
  considerations = $aha_considerations$["falls_elevation","respiratory","rolling_scaffolds","fixed_scaffolds","aerial_lifts"]$aha_considerations$::jsonb,
  equipment_rows = $aha_equipment$[{"id":"48e46dfa-def3-496b-9111-ee03ef0705ff","equipment":"Scissor lift","training":"Scissor lift certification required for all operators; documentation provided","inspection":"Inspect on delivery and before each shift; red-tag defects until repaired"},{"id":"a2dfc00d-9f22-49dc-82b4-54ea9bf74e00","equipment":"Boom lift","training":"Boom lift certification required for all operators; documentation provided","inspection":"Inspect on delivery and before each shift; red-tag defects until repaired"},{"id":"0a20b698-9a8b-4b0e-9b1d-b648512f8973","equipment":"Rolling scaffold","training":"Scaffold certification required for all users; documentation provided","inspection":"Inspect on delivery and before each shift by a competent person; red-tag defects"},{"id":"805d4084-6c28-4038-b89f-4e3ea4302565","equipment":"Ladder","training":"Ladder safety training; documentation provided","inspection":"Inspect for defects and damage before use; red-tag defects"},{"id":"d61e2efd-c16a-4e37-8509-932e1d3730e5","equipment":"Power tools","training":"Authorized to use","inspection":"Inspect daily for broken or loose parts; red-tag and replace defects"},{"id":"983c6e43-3fb9-4879-843e-299248eb8a90","equipment":"Hand tools","training":"Authorized to use","inspection":"Inspect daily for broken or loose parts; red-tag and replace defects"},{"id":"18e87c78-69a2-4338-9d66-3573bf6513b8","equipment":"Airless sprayer / paint sprayer","training":"Trained by supervisor before use; authorized to use","inspection":"Inspect daily for damaged parts and cords; tag, remove, and replace defects"},{"id":"a36f7b72-9b0e-400b-820a-98091e0797fb","equipment":"Respirator","training":"Medical clearance, fit test, and training on use and maintenance","inspection":"Inspect before each use; replace filters on mfr. schedule; clean daily; store sealed"},{"id":"8a8a6b1e-e7ec-48aa-928c-52b0bf84ae82","equipment":"Personal fall protection system","training":"Trained in donning and use before starting work","inspection":"Inspect before each use; SRL-LE (ANSI Z359.14) for leading edge; red-tag defects"}]$aha_equipment$::jsonb,
  competent_persons = $aha_persons$[{"id":"23c43f4c-6a6d-4cac-8092-b1c2c72e972e","activity":"Supervise safety on the job site","qualification":"competent","na":false,"note":"","employee":""},{"id":"643c197d-21de-4abb-9497-5420b4b405e0","activity":"First aid / CPR","qualification":"trained","na":false,"note":"","employee":""},{"id":"7f1b8725-13d3-4e34-a027-82dc4e4ac18c","activity":"Fall protection supervision / inspection of fall protection equipment","qualification":"competent","na":false,"note":"Inspected by user before each use","employee":""},{"id":"72658901-0f57-439c-9b92-6cec30062d8b","activity":"Fall protection plan development / anchors","qualification":"qualified","na":false,"note":"If needed","employee":""},{"id":"1ea1ced8-4ad5-4b34-95ca-1eaf475b20bb","activity":"Ladder inspections","qualification":"competent","na":false,"note":"Inspected by user before each use","employee":""},{"id":"7b8633c9-7448-4aef-a667-5fde80a9bb80","activity":"Supervise scaffold erection / dismantlement","qualification":"competent","na":false,"note":"If needed","employee":""},{"id":"42868ea8-ddc9-41aa-add5-925afbf93787","activity":"Rolling / mobile scaffold inspection","qualification":"competent","na":false,"note":"Used by certified operator","employee":""},{"id":"022f1609-419e-4b15-bae0-8a4c37df83ce","activity":"Scaffold inspection","qualification":"competent","na":false,"note":"Inspected by user before each use","employee":""},{"id":"1a0c99e3-8cd4-4b91-95dd-fb9529862f4b","activity":"Scissor lift / boom lift use","qualification":"competent","na":false,"note":"Used by certified operator","employee":""},{"id":"4fc7b7bf-26ec-4133-932e-d634d334f949","activity":"Powder-actuated tool use","qualification":"qualified_licensed","na":true,"note":"","employee":""},{"id":"b1dea2d0-ac07-4392-8173-ba210d2f782a","activity":"Evaluate silica exposures and implement exposure control plan","qualification":"competent","na":true,"note":"","employee":""}]$aha_persons$::jsonb
where name = 'Paints & coatings';

update public.aha_library as lib
set considerations = spec.value
from jsonb_each($aha_by_slug${"surface-prep":["health_hazards"],"brush-roll":["falls_elevation","rolling_scaffolds"],"airless-spray":["respiratory"],"wallcovering-install":["falls_elevation","rolling_scaffolds"],"scissor-lift":["falls_elevation","aerial_lifts"],"occupied-spaces":["public_exposure"],"wallcovering-removal":["health_hazards"],"lead-paint":["asbestos_lead","respiratory","hazmat_waste","health_hazards"],"exterior-painting":["falls_elevation","public_exposure","aerial_lifts"],"hp-coatings":["respiratory","health_hazards"],"floor-coatings":["respiratory","health_hazards"],"steel-deck":["falls_elevation","aerial_lifts","respiratory","health_hazards"],"active-facility":["energized_loto","work_permits"],"boom-lift":["falls_elevation","aerial_lifts"],"heat-illness":["health_hazards"]}$aha_by_slug$::jsonb) as spec(slug, value)
where lib.slug = spec.slug;

notify pgrst, 'reload schema';
